### ISSUE TITLE
Using Symfony configuration rather than "plugins"

### ISSUE THREAD

**Issue by AlmogBaku** [OAuth2-Framework/server-bundle#16]
Following our quick convo on the FOSOAuthServerBundle repo:

Why not using the Symfony convention of: configuration, "extending", and overriding parameters which specify the classes?

**Comment by Spomky** [comment]
Hi,

I am glad to see you again and continue to talk about this topic.
This bundle uses plugins and I know this is not common. Bundles are supposed to follow conventions you listed: configuration reusable principle...

At the beginning of this project, I created several bundles: one for each component of an OAuth2 server. The main problem is that it is really difficult to maintain more than 10 small bundles.
I found [this blog post](http://php-and-symfony.matthiasnoback.nl/2015/07/a-plugin-system-for-bundles/) from Matthis Noback, a Symfony Expert, and I discovered a new way to solve my problem: create a bundle with plugins.

If you read carefully the blog post, you will find that my bundle and all plugins do not break Symfony conventions: you can still overide any file or parameter.

**Comment by Spomky** [comment]
Hi,

I am completely rewriting the library used by this bundle.
Many changes will be done for this bundle and, particularly, I will drop the plugin system off for all components included in this package.

I let this issue opened. I will close it once the job is done.
