### ISSUE TITLE
simple working exemple

### ISSUE THREAD

**Issue by JesusTheHun** [OAuth2-Framework/server-bundle#52]
Hi !

Can you provide, on another repository, a very basic example of how to use your bundle ? You've made serious progress on the documentation, yet it's split everywhere, not easy to quickstart !

**Comment by Spomky** [comment]
Hi (again),

As explained in the other discussion, I cannot create any basic example as the library and the bundle are not stable.
The documentation will be completely rewritten as a lot of changes have been done.
I completely reviewed the way the library works: now there are only Http Middlewares and is CQRS+Event Sourcing compliant.
Anyway, you can contact me directly on [Gitter](https://gitter.im/OAuth2-Framework), I will explain in details the reasons of these modifications.
